-- CPE106L Laboratory 5 - Database Schema
-- SQLServerColonial.sql equivalent for SQLite

-- Create Customer table
CREATE TABLE IF NOT EXISTS Customer (
    CUSTOMER_NUM INTEGER PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(100) NOT NULL,
    ADDRESS VARCHAR(200),
    CITY VARCHAR(50),
    STATE VARCHAR(2),
    POSTAL_CODE VARCHAR(10),
    PHONE VARCHAR(15)
);

-- Create Guide table  
CREATE TABLE IF NOT EXISTS Guide (
    GUIDE_NUM INTEGER PRIMARY KEY,
    LAST_NAME VARCHAR(50) NOT NULL,
    FIRST_NAME VARCHAR(50) NOT NULL,
    ADDRESS VARCHAR(200),
    CITY VARCHAR(50), 
    STATE VARCHAR(2),
    POSTAL_CODE VARCHAR(10),
    PHONE_NUM VARCHAR(15),
    HIRE_DATE DATE
);

-- Create Trip table
CREATE TABLE IF NOT EXISTS Trip (
    TRIP_ID INTEGER PRIMARY KEY,
    TRIP_NAME VARCHAR(100) NOT NULL,
    START_LOCATION VARCHAR(100),
    STATE VARCHAR(2),
    DISTANCE REAL,
    MAX_GRP_SIZE INTEGER,
    TYPE VARCHAR(50),
    SEASON VARCHAR(20)
);

-- Create Reservation table
CREATE TABLE IF NOT EXISTS Reservation (
    RESERVATION_ID INTEGER PRIMARY KEY,
    TRIP_ID INTEGER,
    TRIP_DATE DATE,
    NUM_PERSONS INTEGER,
    TRIP_PRICE REAL,
    OTHER_FEES REAL,
    CUSTOMER_NUM INTEGER,
    FOREIGN KEY (TRIP_ID) REFERENCES Trip(TRIP_ID),
    FOREIGN KEY (CUSTOMER_NUM) REFERENCES Customer(CUSTOMER_NUM)
);

-- Create Trip_Guides table (junction table for many-to-many relationship)
CREATE TABLE IF NOT EXISTS Trip_Guides (
    TRIP_ID INTEGER,
    GUIDE_NUM INTEGER,
    PRIMARY KEY (TRIP_ID, GUIDE_NUM),
    FOREIGN KEY (TRIP_ID) REFERENCES Trip(TRIP_ID),
    FOREIGN KEY (GUIDE_NUM) REFERENCES Guide(GUIDE_NUM)
);
